version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.5.0 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5432:5432
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.18
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - fastgpt
    command: mongod --keyFile /data/mongodb.key --replSet rs0
    environment:
      # 默认的用户名和密码，只有首次允许有效
      - MONGO_INITDB_ROOT_USERNAME=myname
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/keyfile:/data/mongodb.key
#   m3e:
#     image: stawky/m3e-large-api
#     container_name: m3e
#     ports:
#       - 6008:6008
#     networks:
#       - fastgpt
#   oneapi:
#     image: justsong/one-api:latest
#     container_name: one-api
#     restart: always
#     command: --log-dir /app/logs
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./oneapi/data:/data
#       - ./oneapi/logs:/app/logs
#     environment:
#       - SQL_DSN=root:mysqlpwd@tcp(mysql:3306)/oneapi  # 修改此行，或注释掉以使用 SQLite 作为数据库
#       - REDIS_CONN_STRING=redis://redis
#       - SESSION_SECRET=random_string  # 修改为随机字符串
#       - TZ=Asia/Shanghai
# #      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
# #      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
# #      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
#     depends_on:
#       - redis
#     healthcheck:
#       test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#     networks:
#       - mysql
#       - fastgpt
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - fastgpt
  # fastgpt:
  #   container_name: fastgpt
  #   image: ghcr.io/labring/fastgpt:latest # git
  #   # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - fastgpt
  #   depends_on:
  #     - mongo
  #     - pg
  #   restart: always
  #   environment:
  #     # root 密码，用户名为: root
  #     - DEFAULT_ROOT_PSW=123456
  #     # 中转地址，如果是用官方号，不需要管。务必加 /v1
  #     - OPENAI_BASE_URL=https://api.openai.com/v1
  #     - CHAT_API_KEY=sk-xxxx
  #     - DB_MAX_LINK=5 # database max link
  #     - TOKEN_KEY=any
  #     - ROOT_KEY=root_key
  #     - FILE_TOKEN_KEY=filetoken
  #     # mongo 配置，不需要改. 用户名myname,密码mypassword。
  #     - MONGODB_URI=mongodb://myname:mypassword@mongo:27017/fastgpt?authSource=admin
  #     # pg配置. 不需要改
  #     - PG_URL=postgresql://username:password@pg:5432/postgres
  #   volumes:
  #     - ./config.json:/app/data/config.json
networks:
  fastgpt:
    driver: bridge
    name: fastgpt
  mysql:
    external: true
    name: mysql
      